" Vundle Pugins
source ~/.vimrc.bundles

" General
set nu
syntax enable


" Plugin Related

" Colorscheme
set background=dark
let g:solarized_termtrans=1
colorscheme solarized

" Airline : Status bar app
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline_theme='jellybeans'
set laststatus=2

" Syntastic : Syntax Check app
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0



" Tagbar : ctags
" sudo apt-get install exuberant-ctags
nmap <F8> :TagbarToggle<CR>






